/Users/punk1290/git/spacetimedb-python-sdk/target/debug/build/thiserror-1841112df2392c68/out